spring:
  # \u914D\u7F6E\u6570\u636E\u6E90
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # \u914D\u7F6Erestful\u8F6C\u6362\u8FC7\u6EE4\u5668
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    # \u914D\u7F6E\u9A7C\u5CF0\u547D\u540D
    map-underscore-to-camel-case: true
    # \u8BBE\u7F6E\u522B\u540D
  type-aliases-package: com.offcn.entity

